version: '3.3'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
        - ./create.sql:/docker-entrypoint-initdb.d/create.sql

  app:
    image: commerce-app 
    environment:
        POSTGRES_PORT: 5432 
        POSTGRES_HOST: db 
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DATABASE: postgres
        PORT: 3000
    ports:
        - 3000:3000